Logging and Checks
Fixed logging issue. Added another check to see if lpadmin adding of printer status fails. This could happen if a PPD is not available for example. Removes printer that is still added even after an error, as this would otherwise prevent a subsequent install attempt from happening.

diff --git a/printer-pkginfo b/printer-pkginfo
--- a/printer-pkginfo
+++ b/printer-pkginfo
@@ -133,10 +133,10 @@ currentVersion="%s"
 
 function exitWithStatus () {
 	if [ $1 -eq 0 ]; then
-		echo "INSTALL REQUIRED!"
+		echo "INSTALL REQUIRED"
+	else
+		echo "NO INSTALL REQUIRED"
 	fi
-	echo "NO INSTALL REQUIRED"
-	
 	echo "-------------------"
 	echo ""
 	exit $1
@@ -248,6 +248,13 @@ printf "Adding $printername... "
     -o printer-is-shared=false \
     -o printer-error-policy=abort-job \
     -E
+
+
+if [ $? -ne 0 ]; then
+	echo "Failed adding printer... Removing... "
+	/usr/sbin/lpadmin -x "$printername"
+	exitWithStatus 1
+fi
 
 # Get list of configured printers 
 CONFIGUREDPRINTERS=$(lpstat -p | grep -w "printer" | awk '{print$2}' | tr '\n' ' ')
